/****** Object:  StoredProcedure [dbo].[spCreate_ZCOPA_02]    Script Date: 10/28/2021 9:53:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:      <Author, , Name>
-- Create Date: <Create Date, , >
-- Description: <Description, , >
-- =============================================
ALTER PROCEDURE [dbo].[spCreate_ZCOPA_02]
AS
BEGIN

	/*CNY*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[CNY_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE)),
		[CNY_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'CNY',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];

	/*HKD*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[HKD_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE)),
		[HKD_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'HKD',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];

	/*THB*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[THB_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE)),
		[THB_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'THB',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];


	/*TWD*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[TWD_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE)),
		[TWD_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'TWD',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];

	/*USD*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[USD_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE)),
		[USD_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'USD',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];

	/*VND*/
	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET 
		[VND_ZCOPAP30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAP30] WHEN '' THEN 0 ELSE [ZCOPAP30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC10] WHEN '' THEN 0 ELSE [ZCOPAC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC11] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC11] WHEN '' THEN 0 ELSE [ZCOPAC11] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC12] WHEN '' THEN 0 ELSE [ZCOPAC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC13] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC13] WHEN '' THEN 0 ELSE [ZCOPAC13] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC14] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC14] WHEN '' THEN 0 ELSE [ZCOPAC14] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC15] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC15] WHEN '' THEN 0 ELSE [ZCOPAC15] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC16] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC16] WHEN '' THEN 0 ELSE [ZCOPAC16] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC17] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC17] WHEN '' THEN 0 ELSE [ZCOPAC17] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC90] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC90] WHEN '' THEN 0 ELSE [ZCOPAC90] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC91] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC91] WHEN '' THEN 0 ELSE [ZCOPAC91] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC92] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC92] WHEN '' THEN 0 ELSE [ZCOPAC92] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC93] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC93] WHEN '' THEN 0 ELSE [ZCOPAC93] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC94] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC94] WHEN '' THEN 0 ELSE [ZCOPAC94] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC95] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC95] WHEN '' THEN 0 ELSE [ZCOPAC95] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC96] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC96] WHEN '' THEN 0 ELSE [ZCOPAC96] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAC97] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAC97] WHEN '' THEN 0 ELSE [ZCOPAC97] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGC10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC10] WHEN '' THEN 0 ELSE [ZCOPAGC10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGC12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC12] WHEN '' THEN 0 ELSE [ZCOPAGC12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGC20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC20] WHEN '' THEN 0 ELSE [ZCOPAGC20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGC22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGC22] WHEN '' THEN 0 ELSE [ZCOPAGC22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM10] WHEN '' THEN 0 ELSE [ZCOPAGM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGM20] WHEN '' THEN 0 ELSE [ZCOPAGM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR10] WHEN '' THEN 0 ELSE [ZCOPAGR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGR12] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR12] WHEN '' THEN 0 ELSE [ZCOPAGR12] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGR20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR20] WHEN '' THEN 0 ELSE [ZCOPAGR20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAGR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAGR22] WHEN '' THEN 0 ELSE [ZCOPAGR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAM10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM10] WHEN '' THEN 0 ELSE [ZCOPAM10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAM20] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAM20] WHEN '' THEN 0 ELSE [ZCOPAM20] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR10] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR10] WHEN '' THEN 0 ELSE [ZCOPAR10] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR21] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR21] WHEN '' THEN 0 ELSE [ZCOPAR21] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR22] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR22] WHEN '' THEN 0 ELSE [ZCOPAR22] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR30] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR30] WHEN '' THEN 0 ELSE [ZCOPAR30] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR31] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR31] WHEN '' THEN 0 ELSE [ZCOPAR31] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR32] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR32] WHEN '' THEN 0 ELSE [ZCOPAR32] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR33] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR33] WHEN '' THEN 0 ELSE [ZCOPAR33] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE)),
		[VND_ZCOPAR40] = CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAR40] WHEN '' THEN 0 ELSE [ZCOPAR40] END,0))*[dbo].[SFGETRATE]([0CURRENCY_CODE],'VND',CAST([0CALMONTH] + '.01' AS DATE))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL];


	UPDATE [dbo].[ZCOPA_M01_Q002_FINAL]
	SET [dbo].[ZCOPA_M01_Q002_FINAL].[ZCOPAQ10] = (0.1) * CONVERT(decimal(38,7),ISNULL(CASE [ZCOPAQ10] WHEN '' THEN 0 ELSE [ZCOPAQ10] END,0))
	FROM [dbo].[ZCOPA_M01_Q002_FINAL]
	WHERE [dbo].[ZCOPA_M01_Q002_FINAL].[0BASE_UOM_CODE] = 'CM2' OR [dbo].[ZCOPA_M01_Q002_FINAL].[0BASE_UOM_CODE] = 'M2';

END
